Add copyToClipboard function, add ability to copy address to clipboar…
skip-mev/skip-go pull request #301
Opened 2024-10-01 19:44 UTC by toddkao

…d in ConnectedWalletModal

2024-10-01 19:46 UTC, toddkao commented on packages/widget-v2/src/modals/ConnectedWalletModal/ConnectedWalletModal.tsx
> +              </TextButton>
this is the only change in this file

2024-10-01 22:04 UTC, codingki requested changes

2024-10-01 22:04 UTC, codingki commented on packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx
> +              onClick={copyToClipboard(source.address)}
you can't do this

```suggestion
              onClick={() => copyToClipboard(source.address)}
```

2024-10-01 22:04 UTC, codingki commented on packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx
> +            onClick={copyToClipboard(source.address)}
```suggestion
            onClick={() => copyToClipboard(source.address)} 
```

2024-10-03 01:25 UTC, codingki approved these changes

2024-10-03 01:28 UTC, merged