fix: speed up time to wallet signing
skip-mev/skip-go pull request #358
Opened 2024-10-10 22:11 UTC by ericHgorski

2024-10-11 20:57 UTC, ericHgorski commented
Time to sign popup: 
before: 8328.5390625 ms
after: 6050.569091796875 ms

And some additional light touch code organization

2024-10-24 22:59 UTC, codingki approved these changes

2024-10-24 23:44 UTC, codingki requested changes
I think we should add params to the cache key

2024-10-29 19:28 UTC, codingki approved these changes

2024-10-30 16:49 UTC, merged