[FRE-1260] Refactor SwapExecutionPage to use route data for asset denoms
skip-mev/skip-go pull request #529
Opened 2024-12-02 21:06 UTC by ericHgorski

2024-12-02 21:06 UTC, ericHgorski commented
operation denom not reliable for axelar transfers

2024-12-03 12:05 UTC, codingki commented
can you give me the example route?

2024-12-03 15:21 UTC, toddkao commented
I would want to know why the first operation's denom_in is wrong

2024-12-03 20:06 UTC, toddkao commented
@ericHgorski alright I spoke to jeremy a bit, I'm reluctant but it's fine to merge this, I just think we need to comment on this being a temp fix

2024-12-03 20:15 UTC, ericHgorski commented
> @ericHgorski alright I spoke to jeremy a bit, I'm reluctant but it's fine to merge this, I just think we need to comment on this being a temp fix

Ill make draft until we've reached a resolution

2024-12-03 21:06 UTC, ericHgorski commented
Ready for re-review

2024-12-04 00:45 UTC, codingki commented
I think we should fix it in `getOperationDetailsAndType`  (utils/clientType.ts)

2024-12-04 00:47 UTC, codingki requested changes
we should fix it in getOperationDetailsAndType (utils/clientType.ts)

2024-12-04 00:47 UTC, codingki commented on packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx
> +  const ibcTransferToAxelarOp = operations.find(op => op.ibcTransferToAxelar);
this can be wrong, if axelarTransfer not in the first operation index it will be wrong

2024-12-04 15:12 UTC, codingki approved these changes
lgtm

2024-12-04 15:14 UTC, merged